name: myenv
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11 
  - pytest=7.1.2
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - pip=23.2.1
  - pip:
    - mlflow==2.5.0
    - azure-ai-ml==1.8.0
    - azureml-mlflow==1.52.0