name: Deploy Model to Azure ML Endpoint

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy model to endpoint
      run: |

        MODEL_NAME="diabetes_model"
        ENDPOINT_NAME="diabetes-mlflow-endpoint"
        WORKSPACE_NAME="diabetes-prod-ws"
        REGISTRY_NAME="RG001"

        az ml model create \
        --name $MODEL_NAME \
        --type "mlflow_model" \
        --path src/model/model \
        --workspace-name $WORKSPACE_NAME \
        --registry-name $REGISTRY_NAME
    
    - name: Create endpoint
      run: |

        az ml online-endpoint create \
        --name $ENDPOINT_NAME \
        -f "src/endpoint.yml" \
        --workspace-name $WORKSPACE_NAME \
        --registry-name $REGISTRY_NAME
    
    - name: Create deployment
      run: |

        az ml online-deployment create \
        --name diabetes-deployment \
        --endpoint $ENDPOINT_NAME \
        -f "src/deploy.yaml" \
        --workspace-name $WORKSPACE_NAME \
        --registry-name $REGISTRY_NAME
        --all-traffic

    - name: Invoke endpoint
      run: |

        ENDPOINT_NAME="diabetes-mlflow-endpoint"

        az ml endpoint invoke \
        --name $ENDPOINT_NAME \
        --request-file src/request.json \
        --response-file src/response.json \
        --workspace-name $WORKSPACE_NAME \
        --registry-name $REGISTRY_NAME