name: Deploy Model to Azure ML Endpoint

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set default environment variables
      run: |

        az account set --subscription bc61aa17-c60a-46b5-a008-fb2aec96507c
        az configure --defaults workspace=diabetes-prod-ws group=RG001

    - name: Deploy model to endpoint
      run: |

        MODEL_NAME="diabetes-prod-model"
        ENDPOINT_NAME="diabetes-mlflow-endpoint"

        # az ml model create \
        # --name $MODEL_NAME \
        # --path azureml://jobs/serene_turtle_y0z2nmszp5/outputs/artifacts/src/model/model \
    
    - name: Create endpoint
      run: |

        # az ml online-endpoint create \
        # --name "diabetes-mlflow-endpoint" \
        # --file "src/endpoint.yml" \
    
    - name: Create deployment
      run: |

        az ml online-deployment create \
        --name diabetes-deployment \
        --file "src/deploy.yml" \
        --all-traffic

    - name: Invoke endpoint
      run: |

        ENDPOINT_NAME="diabetes-mlflow-endpoint"

        az ml endpoint invoke \
        --name $ENDPOINT_NAME \
        --request-file src/request.json \
        --response-file src/response.json \