name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Trigger Azure ML job
      run: |
        az ml job create --subscription bc61aa17-c60a-46b5-a008-fb2aec96507c --resource-group RG001 --wor
        kspace-name WS001 --file "/workspaces/azml-github_actions-cicd/src/job.yml"


