name: Run tests on Pull Request

on:
  pull_request:
    branches: 
      - main

jobs:
  tests:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Install pytest
      run: |
        python -m pip install pytest
    - name: Run pytest
      run: |
        pytest tests/


